"""add skill_effects table

Revision ID: 3b29d072e726
Revises: 4f0cde3d6140
Create Date: 2026-07-24 18:29:50.566698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b29d072e726'
down_revision: Union[str, Sequence[str], None] = '4f0cde3d6140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_effects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('effect_type', sa.Enum('PROJECTILE_COUNT', 'BOUNCE_COUNT', 'ATTACK_SPEED_MULTIPLIER', 'CRIT_CHANCE_BONUS', 'CRIT_DAMAGE_BONUS', 'DEFENSE_BONUS', 'MAX_HP_BONUS', 'DODGE_BONUS', 'MOVEMENT_SPEED_BONUS', 'RESOURCE_GAIN_BONUS', 'LIFE_STEAL_BONUS', name='effect_type'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('value >= 0', name=op.f('ck_skill_effects_value_non_negative')),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_skill_effects_skill_id_skills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_effects'))
    )
    op.create_index(op.f('ix_skill_effects_skill_id'), 'skill_effects', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_effects_skill_id'), table_name='skill_effects')
    op.drop_table('skill_effects')
    # ### end Alembic commands ###
