"""add rune effects table and drop runes effect_value

Revision ID: 638a7776c658
Revises: 3b29d072e726
Create Date: 2026-07-25 18:49:48.541461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '638a7776c658'
down_revision: Union[str, Sequence[str], None] = '3b29d072e726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Note for PostgreSQL: `effect_type`'s native enum type was first
    created by the earlier `skill_effects` migration with fewer members.
    Creating `rune_effects` here re-declares the same enum name with the
    full, wider member list — SQLAlchemy/Alembic does not auto-widen an
    existing native Postgres enum type, so on Postgres this requires
    manually running `ALTER TYPE effect_type ADD VALUE 'x'` (one
    statement per new member, outside a transaction) before this
    migration, or recreating the type. SQLite has no native enum type
    (see the CREATE TABLE DDL: `effect_type` is a plain VARCHAR with no
    CHECK constraint), so this is a no-op there — the primary supported
    path for this project per docs/installation.md.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rune_effects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rune_id', sa.Integer(), nullable=False),
    sa.Column('effect_type', sa.Enum('PROJECTILE_COUNT', 'BOUNCE_COUNT', 'ATTACK_SPEED_MULTIPLIER', 'CRIT_CHANCE_BONUS', 'CRIT_DAMAGE_BONUS', 'DEFENSE_BONUS', 'MAX_HP_BONUS', 'DODGE_BONUS', 'MOVEMENT_SPEED_BONUS', 'RESOURCE_GAIN_BONUS', 'LIFE_STEAL_BONUS', 'ATTACK_BONUS', 'CIRCLE_DAMAGE_BONUS', 'SPRITE_DAMAGE_BONUS', 'PLANT_DAMAGE_BONUS', 'ICE_DAMAGE_BONUS', 'POISON_DAMAGE_BONUS', 'LIGHTNING_DAMAGE_BONUS', 'FIRE_DAMAGE_BONUS', name='effect_type'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('value >= 0', name=op.f('ck_rune_effects_value_non_negative')),
    sa.ForeignKeyConstraint(['rune_id'], ['runes.id'], name=op.f('fk_rune_effects_rune_id_runes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rune_effects'))
    )
    op.create_index(op.f('ix_rune_effects_rune_id'), 'rune_effects', ['rune_id'], unique=False)
    op.drop_column('runes', 'effect_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runes', sa.Column('effect_value', sa.FLOAT(), nullable=False))
    op.drop_index(op.f('ix_rune_effects_rune_id'), table_name='rune_effects')
    op.drop_table('rune_effects')
    # ### end Alembic commands ###
