"""create phase 1 catalog and user account schema

Revision ID: a4dd33969a4f
Revises: 
Create Date: 2026-07-24 14:55:14.636619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4dd33969a4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amulets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rarity', sa.Enum('COMMON', 'RARE', 'EPIC', 'LEGENDARY', 'MYTHIC', 'CHAOTIC', name='rarity_amulet'), nullable=False),
    sa.Column('primary_stat', sa.Enum('ATTACK', 'HEALTH', 'DEFENSE', 'CRIT_CHANCE', 'CRIT_DAMAGE', 'ATTACK_SPEED', 'MOVEMENT_SPEED', 'LIFE_STEAL', 'DODGE', 'RESOURCE_GAIN', name='stat_type_amulet'), nullable=False),
    sa.Column('primary_stat_value', sa.Float(), nullable=False),
    sa.Column('special_effect', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_amulets'))
    )
    op.create_index(op.f('ix_amulets_name'), 'amulets', ['name'], unique=True)
    op.create_table('armor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slot', sa.Enum('HELMET', 'CHEST', 'GLOVES', 'BOOTS', name='armor_slot'), nullable=False),
    sa.Column('rarity', sa.Enum('COMMON', 'RARE', 'EPIC', 'LEGENDARY', 'MYTHIC', 'CHAOTIC', name='rarity_armor'), nullable=False),
    sa.Column('base_defense', sa.Float(), nullable=False),
    sa.Column('base_hp', sa.Float(), nullable=False),
    sa.Column('special_effect', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_armor'))
    )
    op.create_index(op.f('ix_armor_name'), 'armor', ['name'], unique=True)
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('boss_name', sa.String(length=100), nullable=True),
    sa.Column('recommended_combat_power', sa.Float(), nullable=False),
    sa.Column('energy_cost', sa.Integer(), nullable=False),
    sa.Column('rewards_summary', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chapters'))
    )
    op.create_index(op.f('ix_chapters_number'), 'chapters', ['number'], unique=True)
    op.create_table('heroes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('hero_class', sa.Enum('WARRIOR', 'MAGE', 'RANGER', 'ASSASSIN', 'SUPPORT', name='hero_class'), nullable=False),
    sa.Column('rarity', sa.Enum('COMMON', 'RARE', 'EPIC', 'LEGENDARY', 'MYTHIC', 'CHAOTIC', name='rarity_hero'), nullable=False),
    sa.Column('base_hp', sa.Float(), nullable=False),
    sa.Column('base_attack', sa.Float(), nullable=False),
    sa.Column('base_defense', sa.Float(), nullable=False),
    sa.Column('base_attack_speed', sa.Float(), nullable=False),
    sa.Column('signature_skill_description', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_heroes'))
    )
    op.create_index(op.f('ix_heroes_name'), 'heroes', ['name'], unique=True)
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rarity', sa.Enum('COMMON', 'RARE', 'EPIC', 'LEGENDARY', 'MYTHIC', 'CHAOTIC', name='rarity_pet'), nullable=False),
    sa.Column('bonus_stat', sa.Enum('ATTACK', 'HEALTH', 'DEFENSE', 'CRIT_CHANCE', 'CRIT_DAMAGE', 'ATTACK_SPEED', 'MOVEMENT_SPEED', 'LIFE_STEAL', 'DODGE', 'RESOURCE_GAIN', name='stat_type_pet'), nullable=False),
    sa.Column('bonus_stat_value', sa.Float(), nullable=False),
    sa.Column('ability_description', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pets'))
    )
    op.create_index(op.f('ix_pets_name'), 'pets', ['name'], unique=True)
    op.create_table('rings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rarity', sa.Enum('COMMON', 'RARE', 'EPIC', 'LEGENDARY', 'MYTHIC', 'CHAOTIC', name='rarity_ring'), nullable=False),
    sa.Column('primary_stat', sa.Enum('ATTACK', 'HEALTH', 'DEFENSE', 'CRIT_CHANCE', 'CRIT_DAMAGE', 'ATTACK_SPEED', 'MOVEMENT_SPEED', 'LIFE_STEAL', 'DODGE', 'RESOURCE_GAIN', name='stat_type_ring'), nullable=False),
    sa.Column('primary_stat_value', sa.Float(), nullable=False),
    sa.Column('special_effect', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rings'))
    )
    op.create_index(op.f('ix_rings_name'), 'rings', ['name'], unique=True)
    op.create_table('runes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rune_type', sa.Enum('OFFENSE', 'DEFENSE', 'UTILITY', name='rune_type'), nullable=False),
    sa.Column('rarity', sa.Enum('COMMON', 'RARE', 'EPIC', 'LEGENDARY', 'MYTHIC', 'CHAOTIC', name='rarity_rune'), nullable=False),
    sa.Column('effect_description', sa.Text(), nullable=True),
    sa.Column('effect_value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runes'))
    )
    op.create_index(op.f('ix_runes_name'), 'runes', ['name'], unique=True)
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('skill_type', sa.Enum('OFFENSIVE', 'DEFENSIVE', 'UTILITY', 'MOVEMENT', name='skill_type'), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills'))
    )
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_table('weapons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('weapon_type', sa.String(length=50), nullable=False),
    sa.Column('rarity', sa.Enum('COMMON', 'RARE', 'EPIC', 'LEGENDARY', 'MYTHIC', 'CHAOTIC', name='rarity_weapon'), nullable=False),
    sa.Column('base_damage', sa.Float(), nullable=False),
    sa.Column('base_attack_speed', sa.Float(), nullable=False),
    sa.Column('crit_chance_bonus', sa.Float(), nullable=False),
    sa.Column('special_effect', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weapons'))
    )
    op.create_index(op.f('ix_weapons_name'), 'weapons', ['name'], unique=True)
    op.create_table('user_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('gold', sa.Integer(), nullable=False),
    sa.Column('gems', sa.Integer(), nullable=False),
    sa.Column('energy', sa.Integer(), nullable=False),
    sa.Column('combat_power', sa.Float(), nullable=False),
    sa.Column('current_chapter_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['current_chapter_id'], ['chapters.id'], name=op.f('fk_user_accounts_current_chapter_id_chapters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_accounts'))
    )
    op.create_index(op.f('ix_user_accounts_display_name'), 'user_accounts', ['display_name'], unique=True)
    op.create_table('user_amulet_ownership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('amulet_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('is_equipped', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['user_accounts.id'], name=op.f('fk_user_amulet_ownership_account_id_user_accounts')),
    sa.ForeignKeyConstraint(['amulet_id'], ['amulets.id'], name=op.f('fk_user_amulet_ownership_amulet_id_amulets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_amulet_ownership')),
    sa.UniqueConstraint('account_id', 'amulet_id', name=op.f('uq_user_amulet_ownership_account_id'))
    )
    op.create_index(op.f('ix_user_amulet_ownership_account_id'), 'user_amulet_ownership', ['account_id'], unique=False)
    op.create_index(op.f('ix_user_amulet_ownership_amulet_id'), 'user_amulet_ownership', ['amulet_id'], unique=False)
    op.create_table('user_armor_ownership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('armor_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('star_level', sa.Integer(), nullable=False),
    sa.Column('is_equipped', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['user_accounts.id'], name=op.f('fk_user_armor_ownership_account_id_user_accounts')),
    sa.ForeignKeyConstraint(['armor_id'], ['armor.id'], name=op.f('fk_user_armor_ownership_armor_id_armor')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_armor_ownership')),
    sa.UniqueConstraint('account_id', 'armor_id', name=op.f('uq_user_armor_ownership_account_id'))
    )
    op.create_index(op.f('ix_user_armor_ownership_account_id'), 'user_armor_ownership', ['account_id'], unique=False)
    op.create_index(op.f('ix_user_armor_ownership_armor_id'), 'user_armor_ownership', ['armor_id'], unique=False)
    op.create_table('user_chapter_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('stars_earned', sa.Integer(), nullable=False),
    sa.Column('cleared', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['user_accounts.id'], name=op.f('fk_user_chapter_progress_account_id_user_accounts')),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name=op.f('fk_user_chapter_progress_chapter_id_chapters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_chapter_progress')),
    sa.UniqueConstraint('account_id', 'chapter_id', name=op.f('uq_user_chapter_progress_account_id'))
    )
    op.create_index(op.f('ix_user_chapter_progress_account_id'), 'user_chapter_progress', ['account_id'], unique=False)
    op.create_index(op.f('ix_user_chapter_progress_chapter_id'), 'user_chapter_progress', ['chapter_id'], unique=False)
    op.create_table('user_hero_ownership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('hero_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['user_accounts.id'], name=op.f('fk_user_hero_ownership_account_id_user_accounts')),
    sa.ForeignKeyConstraint(['hero_id'], ['heroes.id'], name=op.f('fk_user_hero_ownership_hero_id_heroes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_hero_ownership')),
    sa.UniqueConstraint('account_id', 'hero_id', name=op.f('uq_user_hero_ownership_account_id'))
    )
    op.create_index(op.f('ix_user_hero_ownership_account_id'), 'user_hero_ownership', ['account_id'], unique=False)
    op.create_index(op.f('ix_user_hero_ownership_hero_id'), 'user_hero_ownership', ['hero_id'], unique=False)
    op.create_table('user_pet_ownership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['user_accounts.id'], name=op.f('fk_user_pet_ownership_account_id_user_accounts')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_user_pet_ownership_pet_id_pets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_pet_ownership')),
    sa.UniqueConstraint('account_id', 'pet_id', name=op.f('uq_user_pet_ownership_account_id'))
    )
    op.create_index(op.f('ix_user_pet_ownership_account_id'), 'user_pet_ownership', ['account_id'], unique=False)
    op.create_index(op.f('ix_user_pet_ownership_pet_id'), 'user_pet_ownership', ['pet_id'], unique=False)
    op.create_table('user_ring_ownership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('ring_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('is_equipped', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['user_accounts.id'], name=op.f('fk_user_ring_ownership_account_id_user_accounts')),
    sa.ForeignKeyConstraint(['ring_id'], ['rings.id'], name=op.f('fk_user_ring_ownership_ring_id_rings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_ring_ownership')),
    sa.UniqueConstraint('account_id', 'ring_id', name=op.f('uq_user_ring_ownership_account_id'))
    )
    op.create_index(op.f('ix_user_ring_ownership_account_id'), 'user_ring_ownership', ['account_id'], unique=False)
    op.create_index(op.f('ix_user_ring_ownership_ring_id'), 'user_ring_ownership', ['ring_id'], unique=False)
    op.create_table('user_rune_ownership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('rune_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('is_equipped', sa.Boolean(), nullable=False),
    sa.Column('socket_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['user_accounts.id'], name=op.f('fk_user_rune_ownership_account_id_user_accounts')),
    sa.ForeignKeyConstraint(['rune_id'], ['runes.id'], name=op.f('fk_user_rune_ownership_rune_id_runes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_rune_ownership')),
    sa.UniqueConstraint('account_id', 'rune_id', name=op.f('uq_user_rune_ownership_account_id'))
    )
    op.create_index(op.f('ix_user_rune_ownership_account_id'), 'user_rune_ownership', ['account_id'], unique=False)
    op.create_index(op.f('ix_user_rune_ownership_rune_id'), 'user_rune_ownership', ['rune_id'], unique=False)
    op.create_table('user_skill_selection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('is_unlocked', sa.Boolean(), nullable=False),
    sa.Column('equipped_slot', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['user_accounts.id'], name=op.f('fk_user_skill_selection_account_id_user_accounts')),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_user_skill_selection_skill_id_skills')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_skill_selection')),
    sa.UniqueConstraint('account_id', 'skill_id', name=op.f('uq_user_skill_selection_account_id'))
    )
    op.create_index(op.f('ix_user_skill_selection_account_id'), 'user_skill_selection', ['account_id'], unique=False)
    op.create_index(op.f('ix_user_skill_selection_skill_id'), 'user_skill_selection', ['skill_id'], unique=False)
    op.create_table('user_weapon_ownership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('weapon_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('star_level', sa.Integer(), nullable=False),
    sa.Column('is_equipped', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['user_accounts.id'], name=op.f('fk_user_weapon_ownership_account_id_user_accounts')),
    sa.ForeignKeyConstraint(['weapon_id'], ['weapons.id'], name=op.f('fk_user_weapon_ownership_weapon_id_weapons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_weapon_ownership')),
    sa.UniqueConstraint('account_id', 'weapon_id', name=op.f('uq_user_weapon_ownership_account_id'))
    )
    op.create_index(op.f('ix_user_weapon_ownership_account_id'), 'user_weapon_ownership', ['account_id'], unique=False)
    op.create_index(op.f('ix_user_weapon_ownership_weapon_id'), 'user_weapon_ownership', ['weapon_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_weapon_ownership_weapon_id'), table_name='user_weapon_ownership')
    op.drop_index(op.f('ix_user_weapon_ownership_account_id'), table_name='user_weapon_ownership')
    op.drop_table('user_weapon_ownership')
    op.drop_index(op.f('ix_user_skill_selection_skill_id'), table_name='user_skill_selection')
    op.drop_index(op.f('ix_user_skill_selection_account_id'), table_name='user_skill_selection')
    op.drop_table('user_skill_selection')
    op.drop_index(op.f('ix_user_rune_ownership_rune_id'), table_name='user_rune_ownership')
    op.drop_index(op.f('ix_user_rune_ownership_account_id'), table_name='user_rune_ownership')
    op.drop_table('user_rune_ownership')
    op.drop_index(op.f('ix_user_ring_ownership_ring_id'), table_name='user_ring_ownership')
    op.drop_index(op.f('ix_user_ring_ownership_account_id'), table_name='user_ring_ownership')
    op.drop_table('user_ring_ownership')
    op.drop_index(op.f('ix_user_pet_ownership_pet_id'), table_name='user_pet_ownership')
    op.drop_index(op.f('ix_user_pet_ownership_account_id'), table_name='user_pet_ownership')
    op.drop_table('user_pet_ownership')
    op.drop_index(op.f('ix_user_hero_ownership_hero_id'), table_name='user_hero_ownership')
    op.drop_index(op.f('ix_user_hero_ownership_account_id'), table_name='user_hero_ownership')
    op.drop_table('user_hero_ownership')
    op.drop_index(op.f('ix_user_chapter_progress_chapter_id'), table_name='user_chapter_progress')
    op.drop_index(op.f('ix_user_chapter_progress_account_id'), table_name='user_chapter_progress')
    op.drop_table('user_chapter_progress')
    op.drop_index(op.f('ix_user_armor_ownership_armor_id'), table_name='user_armor_ownership')
    op.drop_index(op.f('ix_user_armor_ownership_account_id'), table_name='user_armor_ownership')
    op.drop_table('user_armor_ownership')
    op.drop_index(op.f('ix_user_amulet_ownership_amulet_id'), table_name='user_amulet_ownership')
    op.drop_index(op.f('ix_user_amulet_ownership_account_id'), table_name='user_amulet_ownership')
    op.drop_table('user_amulet_ownership')
    op.drop_index(op.f('ix_user_accounts_display_name'), table_name='user_accounts')
    op.drop_table('user_accounts')
    op.drop_index(op.f('ix_weapons_name'), table_name='weapons')
    op.drop_table('weapons')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_runes_name'), table_name='runes')
    op.drop_table('runes')
    op.drop_index(op.f('ix_rings_name'), table_name='rings')
    op.drop_table('rings')
    op.drop_index(op.f('ix_pets_name'), table_name='pets')
    op.drop_table('pets')
    op.drop_index(op.f('ix_heroes_name'), table_name='heroes')
    op.drop_table('heroes')
    op.drop_index(op.f('ix_chapters_number'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_armor_name'), table_name='armor')
    op.drop_table('armor')
    op.drop_index(op.f('ix_amulets_name'), table_name='amulets')
    op.drop_table('amulets')
    # ### end Alembic commands ###
